name: BUILD APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - uses: game-ci/unity-builder@v2.0.4
        env:
           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
            targetPlatform: Android
            buildMethod: Build.APK
      
      - uses: actions/upload-artifact@v2.2.4
        with:
            name: build
            path: build
